version = 0.1

[default.deploy.parameters]
stack_name = "qrshort"
resolve_s3 = true
s3_prefix = "qrshort"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = "BaseUrl=https://qr.zzzzico.click DomainName=qr.zzzzico.click"

[default.global.parameters]
region = "ap-northeast-1"
